apiVersion: v1alpha1
generated: "2018-06-13T09:24:07.392654524Z"
kind: RepositoryContent
services:
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: azure
    platforms:
      - linux
  spec:
    description: Azure configuration
    icon: https://raw.githubusercontent.com/sixeyed/app-template-azure/master/img/azure.png
    source:
      image: sixeyed/app-template-azure-svc
    title: Azure 
    parameters:
    - name: region
      defaultValue: eastus
      description: Azure region
      type: string
    - name: resourceGroup
      description: Azure resource group name
      type: string
    - name: subscription
      description: Azure subscription ID
      type: string
    - name: spName
      description: Service Principal Name
      type: string
    - name: spAppId
      description: Service Principal App ID
      type: string
    - name: spTenant
      description: Service Principal tenant
      type: string
    - name: spPassword
      description: Service Principal password
      type: string
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: cosmosdb
    platforms:
      - linux
  spec:
    description: Cosmos DB
    icon: https://raw.githubusercontent.com/sixeyed/app-template-azure/master/img/cosmos-db.png
    source:
      image: sixeyed/app-template-azure-cosmosdb-svc
    title: Azure Cosmos DB database
    parameters:
    - name: cosmosDbAccount
      description: Cosmos DB database name
      type: string
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: bulletinboard
    platforms:
      - linux
  spec:
    description: Node JS Bulletin Board sample app
    icon: https://raw.githubusercontent.com/sixeyed/app-template-azure/master/img/nodejs.png
    source:
      image: sixeyed/app-template-azure-bulletin-board-svc
    title: Bulletin Board
    parameters:
    - name: nodeVersion
      description: Node version
      type: enum
      values:
      - value: "10.15.3"
        description: "10"
      - value: "9"
        description: "9"
      - value: "8"
        description: "8"
    - name: externalPort
      defaultValue: "8081"
      description: External port      
      type: hostPort
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: functions-api
    platforms:
      - linux
  spec:
    description: Azure Functions API for Cosmos DB
    icon: https://raw.githubusercontent.com/sixeyed/app-template-azure/master/img/azure-functions.png
    source:
      image: sixeyed/app-template-azure-functions-api-svc
    title: Azure Functions
    parameters:
    - name: storageAccount
      description: Storage Account name
      type: string
    - name: appName
      description: Functions App name
      type: string
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: active-directory
    platforms:
      - linux
  spec:
    description: Active Directory Domain Controller
    icon: https://raw.githubusercontent.com/sixeyed/app-template-azure/master/img/active-directory.png
    source:
      image: stevenfollis/app-template-azure-active-directory
    title: Active Directory
    parameters:
    - name: adminUsername
      description: Admin Username
      type: string
    - name: adminPassword
      description: Admin Password
      type: string
    - name: domainName
      description: Domain FQDN
      type: string
    - name: dnsPrefix
      description: DNS Prefix
      type: string
templates:
- apiVersion: v1alpha1
  kind: ApplicationTemplate
  metadata:
    name: bulletin-board
    platforms:
    - linux
  spec:
    description: Bulletin Board sample app connected to Azure services
    services:
    - name: azure
      serviceId: azure
      parameters:
        region: westeurope 
    - name: cosmos
      serviceId: cosmosdb
    - name: functions-api
      serviceId: functions-api
    - name: bulletin-board
      serviceId: bulletinboard
      parameters:
        nodeVersion: 10.15.3
    title: NodeJS with Azure Cosmos DB back-end and Azure Functions API